### ISSUE TITLE
Preview iframe can't render in Chrome 33

### ISSUE THREAD

**Issue by Layzie** [jacobrask/styledocco#111]
I'm using Chrome 32.0.1700.77 (Official Build 244503).
Iframe is blocked cause of CORS. The error message is below.

```
Uncaught SecurityError: Blocked a frame with origin "http://localhost:10080" from accessing a frame with origin "null".  The frame requesting access has a protocol of "http", the frame being accessed has a protocol of "data". Protocols must match.
```

Above message has occured in my local server, but [styledocco's demo site](http://jacobrask.github.io/styledocco/) has same error.

![styledocco](https://f.cloud.github.com/assets/844804/1928097/ed57605a-7e74-11e3-89a5-7bf4256cffc0.png)

I think this problem is related #100.

**Comment by theleanship** [comment]
I'm experiencing this as well, have only been able to get round it by disabling the same origin policy in chrome. Anyone else have work arounds?

**Comment by chrisvdp** [comment]
I am also getting it in Chrome 32 and Chrome Canary, but not Safari or Firefox, on OS X 10.9.1

**Comment by theleanship** [comment]
I applied the changes of this commit https://github.com/jacobrask/styledocco/commit/9e01c8cb4f8d7dc0565783929516a58721e1815d from #100 and it seems to fix the problem. This change doesn't seem to have been released yet though.

**Comment by Layzie** [comment]
@isnotahippy 
Oh, I got it. I misunderstood fixed commit had been released already.

Thank you.

**Comment by stefanjudis** [comment]
Hey guys, any news on that one?

Not working anymore in Chrome + Chrome Canary since today.

Fix by @isnotahippy does not work.

**Comment by stefanjudis** [comment]
Just for more information, the exception in console.

```
Uncaught SecurityError: Blocked a frame with origin "http://br.yves.dev" from accessing a frame with origin "null".  The frame requesting access has a protocol of "http", the frame being accessed has a protocol of "data". Protocols must match.

got exception when trying to postMessage from http://br.yves.dev/styleguide/components-buttons.html to data://text/html, 
DOMException {message: "Invalid target origin 'data://text/html,' in a call to 'postMessage'.", name: "SyntaxError", code: 12, stack: "Error: Invalid target origin 'data://text/html,' i…mb/2.8.2_0/generated/extension_properties.js:45:3", INDEX_SIZE_ERR: 1…}
```

**Comment by Layzie** [comment]
@stefanjudis 

I'm work well using  9e01c8c.

Can you try to put below code in your  `package.json`?

``` json
"devDependencies": {
  "styledocco": "git://github.com/jacobrask/styledocco.git"
}
```

Then `npm install` again.

**Comment by marrs** [comment]
I've published a new release with the latest fixes in. I'm closing the ticket for now but please re-open if you are still having issues, and provide details about your browser and its version number.

**Comment by Layzie** [comment]
@marrs 
Thanks for release.:+1:

**Comment by SN81** [comment]
Unfortunable the bug isn't fixed yet. Got the same problem with chrome version 38.0.2125.104
Can anybody help?

**Comment by gorioli** [comment]
Having the same bug after browsing StyleDocco examples at GitHub using Chrome Version 39.0.2171.95. The message I see on my Console is:

```
Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://jacobrask.github.io" from accessing a frame with origin "null".  The frame requesting access has a protocol of "http", the frame being accessed has a protocol of "data". Protocols must match.
```
