### ISSUE TITLE
setting custom --tmpl path does not have effect for docs.css

### ISSUE THREAD

**Issue by aripalo** [jacobrask/styledocco#14]
So if I set a custom path to template files with --tmpl it works for README.md and docs.jade (so the output will use the customized versions), but the output documentation will still only use the styledocco default docs.ss, not the one in path specified with --tmpl option.

Would appreciate a lot if it did use it! :) Anyway great work with Styledocco, it's exactly what I needed for my LESS documentation.

**Comment by jacobrask** [comment]
Appreciate the feedback and report, keep it coming as you stumble upon stuff!

This should now be fixed and I will release a new version soon. I'll notify you here when it's out.

**Comment by jacobrask** [comment]
Just released 0.2.3
