### ISSUE TITLE
Preserving .LESS Comments

### ISSUE THREAD

**Issue by aarr0n** [jacobrask/styledocco#16]
Although I indent stylesheet-only comments correctly in my .LESS files, when they're converted to css these indents are removed and so the comments are shown in the generated styleguide.

This maybe a .LESS question, but wondering if theres a workaround/fix?

**Comment by jacobrask** [comment]
I guess you are running StyleDocco against the compiled CSS files? The preferred way would be to run it on the Less file instead.

Unfortunately StyleDocco is currently not well tested with Less, as I am using SASS, but if you encounter any issues (bugs or feature requests) with StyleDocco + Less it would be appreciated if you'd report them.

One other way would be to have a different way of ignoring a comment than prefixing it with whitespace. It would add more complexity though, something I'd like to avoid, but if it's necessary we should come up with some decent syntax for it.
