### ISSUE TITLE
Do not generate blocks .styledocco-example for Markdown files

### ISSUE THREAD

**Issue by piouPiouM** [jacobrask/styledocco#17]
It would be appreciated not generate `div.styledocco-example` for Markdown files.
Indeed, the code blocks are duplicated and ugly.

For example, in my `README.md` I wrote the following lines:

```
compass compile -c sass/theme.rb -e production -f
open -a ImageOptim.app assets/img/*.png
```

Unfortunately, StyleDocco generates an aditional `<div class="styledocco-example"/>` that displays the code on a line:

```
compass compile -c sass/theme.rb -e production -f open -a ImageOptim.app assets/img/*.png
```

**Comment by jacobrask** [comment]
Fixed in 0.3.0, thanks for the report
