### ISSUE TITLE
Add a flag to proccess Sass partials

### ISSUE THREAD

**Issue by piouPiouM** [jacobrask/styledocco#18]
It is now convenient to separate the Sass sources logically into a multitude of  partials. As a result, much of the documentation is found in the partials, which is absent from the generated documentation.

**Comment by jacobrask** [comment]
I might actually remove the ignore rule entirely instead, it's only there for SASS and not for Less/Stylus anyway.

**Comment by jacobrask** [comment]
Fixed, will be out with 0.3.0
