### ISSUE TITLE
StyleDocco fails on commented data attribute

### ISSUE THREAD

**Issue by klaascuvelier** [jacobrask/styledocco#24]
Making docs fails on a file when there's a commented type-attribute.
Like here:

```
/*span.filter-field, span.filter-field input[type="text"] {
    background-color: #999;
}*/
```

I get this error:

> node.js:201
>         throw e; // process.nextTick error, or 'error' event on first tick
>               ^
> TypeError: Cannot read property 'type="text"' of undefined

**Comment by jacobrask** [comment]
Thanks for your report, that's weird. I'll look into it as soon as possible. If you want to investigate it further yourself I believe it might have to do with the marked parser (or how it's called/handled in StyleDocco). https://github.com/jacobrask/styledocco/blob/master/src/parser.coffee#L46

It seems to think that `input` is a JavaScript object...
