### ISSUE TITLE
Styledocco does not pick up css files

### ISSUE THREAD

**Issue by PhillyWebGuy** [jacobrask/styledocco#26]
I'm running this on Windows with node.js from a bash shell.

I type the following:

styledocco -n "test styledocco" -o docs -s css

css is a subfolder of my pwd.

In the css folder I have a file called screen.css with the following content:

/\* Provides extra visual weight and identifies the primary action in a set of buttons.

```
<button class="btn primary">Primary</button> */
```

.btn.primary {
    background: steelblue;
    color: snow;
    border: 1px solid steelblue;
}

After executing, I get the following output from my shell:

styledocco: index.html -> docs\index.html
styledocco: writing docs\docs.css
styledocco: writing docs\docs.js

I open up the index.html file and there's no evidence of my css. I just get what I suppose is the generic page. On the left, the menu says "Test Styledocco"

The only other content says this:

Style Guide

Use the menu to the left to navigate.  Please add a Readme file to your project to update this message. The Readme file will be parsed with Markdown. 

What am I doing wrong? How do I styledocco?

**Comment by jacobrask** [comment]
Hi,

I just realized the documentation is poorly written, I will fix it asap. The -s option is to add custom CSS for displaying the _documentation_, not the CSS to generate the documentation _from_.

Try without the -s flag:

```
styledocco -n "test styledocco" -o docs css
```

**Comment by PhillyWebGuy** [comment]
Nice, that syntax works. Thanks for your quick reply!
