### ISSUE TITLE
Parse only .css files

### ISSUE THREAD

**Issue by tbleckert** [jacobrask/styledocco#29]
Hi!

I'm working on a project where I have **.scss** and **.css** files in the same directory. Running styledocco in that folder will generate an error. Eg:

`styledocco --name "A cool name" .`

So I thought that maybe I need to say that I only want to parse .css files, so I did this `styledocco --name "A cool name" *.css`. That kind of worked but styledocco only generated the first css file found in this directory.

Is this i bug or am I doing it wrong? I should say that this is very critical for our project and it would be awesome if you could check this as soon as possible.

Keep up the good work!

**Comment by jacobrask** [comment]
Great find, I will add glob matching (*.css etc) to StyleDocco asap.
