### ISSUE TITLE
base64 is no longer shortened

### ISSUE THREAD

**Issue by tbleckert** [jacobrask/styledocco#33]
Hi!

First of all thanks for the last update, really cool stuff in there!

I've noticed that base64 strings are no longer shortened, before they looked like this: **data:image/png;base64,...**, but now everything is there which makes the css in some places really really long.

Another thing I saw is that the photoshop-ish background behind examples are gone. Is that a feature or a bug?

Thanks! Your work is really great!

**Comment by jacobrask** [comment]
Thanks, I rewrote StyleDocco and forgot to re-add the base64 shortener. Do you use the CSS code column much? Some people have suggested that I remove it.

Regarding the checkerboard background, did you like it? I added it to be able to see the edges of (white) elements, but I got some negative feedback on it and removed it.

I am planning to handle the examples in a different way soon. They will be in iframes instead, so whatever background is specified in your stylesheet will be applied to the example.
