### ISSUE TITLE
Documenting modularized css

### ISSUE THREAD

**Issue by chrisjaure** [jacobrask/styledocco#35]
It seems like this project is geared towards smaller projects and could use some improvements for larger code bases. 

For example, I've got close to a hundred css files that I've started documenting for StyleDocco. Here are some issues I've encountered:
- My css is modular and some modules depend on others, but I can only include one css file globally. I guess the easiest solution would be to include all css that's processed.
- I don't need docs for all files. A more granular method to process specific files would be appreciated.
- Some things depend on javascript as well... I'd like to be able to include those for functionality, not necessarily to document.
- I don't always want code examples to be rendered. In my case, I've got some php I'd like to include as an example. I know I can hide that comment entirely from StyleDocco, but I still want it to appear with the rest of the documentation.

I think that covers all of it. Let me know if any of these are already possible; I don't know all of version 0.4's new features.

Note: None of this are stopping me from using StyleDocco, they'd just be nice to have :)

**Comment by chrisjaure** [comment]
One more thing was dealing with relative urls. I had to write a preprocessor just to rewrite relative urls to absolute paths since I won't be hosting the style docs on the same domain.

**Comment by eskimoblood** [comment]
Include all processed css would be great. Think about a css file where I only declare different image sizes. In another file I will show an composite example where I need a specific image size. 

Also linking between parts of the parts of the doc would be cool. So maybe you could change the way the different sections get there ids aka `#section-1`. Using this ids to link will become unmaintainable after a while. So my idea is to convert every md headline into anker using the head text as id, so 

```
##A header 
```

will become 

```
<h2 id="a-header"><a href="#a-header">A header</a></h2>
```

**Comment by jacobrask** [comment]
Thanks for all your great suggestions.
1. You mean to include the CSS from all files, in all files? Maybe we could reuse the `--include` option to do this if you don't specify any parameters. That way we avoid adding more options. Another option is to have a custom `styledocco_include` option in the beginning of all CSS files, to include CSS or JS files. I prefer introducing as little StyleDocco specific syntax as possible though.
2. I think this should be done outside of StyleDocco, using `find` or similar, to avoid introducing more complexity. I could add examples of using `find` to the documentation.
3. See (1)
4. Should be an easy fix. The syntax will be like on GitHub:
   
   ``````
   ```php
   code
   ```
   ``````
   
   and only code examples with type HTML or no type will get embedded examples.

@eskimoblood I agree and will add that asap.

**Comment by chrisjaure** [comment]
1. Is there any reason including all css in all files by default would be undesired? I agree that adding specific syntax isn't a good solution.
2. Using `find` or similar would be fine. The current syntax for that doesn't seem intuitive though. Would it be possible to pipe the files to styledocco? E.g. `find . -name "*.css" -not -path "*jquery*" | styledocco -n Name`
3. Might solve the problem if `--include` could be made to accept any number of css or js files.
4. Sounds good!

**Comment by jacobrask** [comment]
Your suggestions are good, and I'll try to implement them asap, but #2 might need some more consideration. Using stdin is tpically for the contents of a file rather than a list of files.

For including all processed CSS, I created #44.

To include any number of extra JavaScript/CSS files, I created #45.
