### ISSUE TITLE
Failure while parsing font property

### ISSUE THREAD

**Issue by eskimoblood** [jacobrask/styledocco#37]
```
font: 16px/1 VAGRundschriftD;
```

will become

```
font:16px/ 1VAGRundschriftD
```

in the minified result, note the `1` after `16px` is moved right to the font name.

**Comment by jacobrask** [comment]
Thanks, I reported this with the CSS minifier StyleDocco uses: https://github.com/kurakin/ncss/issues/2

**Comment by jacobrask** [comment]
It's now fixed in ncss

**Comment by jacobrask** [comment]
v0.5 is now released with a fix for this bug. I'd appreciate if you reported any further issues you might have with StyleDocco. Thanks.
