### ISSUE TITLE
Move the body styles to the example container

### ISSUE THREAD

**Issue by eskimoblood** [jacobrask/styledocco#39]
I've develop a side with black background and VAG Rounded bold as main font. At the moment the black background is ignored the font works in my example but the bold font-weight effects the whole side, so all my code examples are **bold**.

So it would be cool if all styles from the `body` section of an stylesheet will be moved to `styledocco-example`.

```
body {
  background: #000;
  font.weight: bold;
  color: #fff;
}

will become 

body {}

.styledocco-example {
  background: #000;
  font.weight: bold;
  color: #fff;
}
```

**Comment by jacobrask** [comment]
Yes, I agree this is a problem. I'm working on putting all examples into separate iframes, so they would get your body styles as well. I hope to be done with that in a couple of weeks.

**Comment by jacobrask** [comment]
v0.5 is now released which I hope have fixed your problem. I'd appreciate if you reported any further issues you might have with StyleDocco. Thanks.
