### ISSUE TITLE
Include multiple files

### ISSUE THREAD

**Issue by tbleckert** [jacobrask/styledocco#40]
Hi!

I was just wondering if it's possible to include multiple files? I've tried comma/space separated files and also multiple --include but no luck.

Thanks!

**Comment by jacobrask** [comment]
Currently not, but after discussions in #35 I've considered other ways to include files. What is your use case? Would it help if all CSS you're documenting would be added to all documentation files?

**Comment by redonkulus** [comment]
+1, usually when building websites you will have multiple CSS files that contain various base and utility level CSS rules (base for font sizes, icons for icon classes, list for list styles, etc). If you want to use these styles in styledocco, you have to either cat these yourself and reference it in the command or pull in the prod combo'd file. Being able to reference command separate list of files would be nice.

**Comment by jacobrask** [comment]
In the next version you will be able to include any number of files. For each file you want to include you add a separate --include flag, so it would be 

```
styledocco --include foo.css --include bar.css --include app.js mycss.css
```

**Comment by jacobrask** [comment]
v0.5 is now released with this feature. I'd appreciate any further feature suggestions you might have. Thanks.
