### ISSUE TITLE
Menu dropdown doesnt display in "master" code

### ISSUE THREAD

**Issue by redonkulus** [jacobrask/styledocco#46]
Cloned master and ran styledocco, but discovered that hovering over menu toggle link doesn't display menu. Simple CSS selector update below fixes it:

.menu > li:hover .dropdown {
  display:block;
}

I could issue pull request but figured this was an easy enough change.

**Comment by jacobrask** [comment]
The dropdown should open on click but not on hover. I think opening on click is a pattern that's getting more common, and shares the UX with operating systems.

**Comment by redonkulus** [comment]
When I tried on click, nothing happened, the href '#'  was followed instead of being intercepted to show the menu.

**Comment by jacobrask** [comment]
Oh, right, when using the master repo you need to run `make` before using styledocco to get the latest version of the documentation client side scripts. I haven't documented that anywhere yet, sorry about that. If that doesn't help, try deleting resources/docs.js and run make again and then run styledocco.
