### ISSUE TITLE
Question: Is it possible to tell styledocco not to render the CSS of a file?

### ISSUE THREAD

**Issue by redonkulus** [jacobrask/styledocco#47]
For example, I have a base.css style sheet that has reset settings and other things that causes styledocco's styling to become malformed.  Is it possible to tell styledocco not to render the stylesheet of the file that is being viewed?

**Comment by jacobrask** [comment]
Have you tried the latest version of StyleDocco? It does not add your CSS to the actual documentation, but only to the previews which are rendered in iframes. Or did I misunderstand?

**Comment by redonkulus** [comment]
Ok upgrading makes this issue go away. 

However, the menu toggle click issue still remains. I upgrading using npm so I didn't run the make file like you mentioned before, is that still necessary if I use npm to install the package?

**Comment by redonkulus** [comment]
Additionally, looks like the --include flag is not adding the files that I specify in the command either.

**Comment by jacobrask** [comment]
Regarding the menu toggle, could it be that you have specified a custom docs.js which doesn't include the new changes added in v0.5.0? If not, can you see if docs.js is completely empty, or if you get any errors in your browser developer tools?

Regarding --include you need to specify one flag per file, so --include file1.css --include file2.css. Does that help?

**Comment by redonkulus** [comment]
You are correct about docs.js, I specified my own that handles creating a table of contents dynamically. In this case, should I move my changes to another .js files and pull that in via the --include flag or should I manually copy the original docs.js into my version?

As for --include, this is the command I'm running:
styledocco -n "CSS Framework" -o ~/doc/ assets/ --include assets/base/css/utility.css -s assets/docs/ --verbose

Output:
styledocco: writing assets/base/css/base.css -> /homes/sbertal/sandbox/style/base-css-base.html
styledocco: writing assets/base/css/form.css -> /homes/sbertal/sandbox/style/base-css-form.html
styledocco: writing assets/base/css/table.css -> /homes/sbertal/sandbox/style/base-css-table.html
styledocco: writing assets/base/css/utility.css -> /homes/sbertal/sandbox/style/base-css-utility.html
styledocco: writing assets/themes/base/css/theme-imagery.css -> /homes/sbertal/sandbox/style/themes-base-css-theme-imagery.html
styledocco: writing assets/themes/base/css/theme.css -> /homes/sbertal/sandbox/style/themes-base-css-theme.html
styledocco: writing /mnt/hut.corp.yahoo.com/vol/vol0/home/sbertal//frontend/assets/index -> /homes/sbertal/sandbox/style/index.html
styledocco: writing docs.js -> /homes/sbertal/sandbox/style/docs.js
styledocco: writing docs.css -> /homes/sbertal/sandbox/style/docs.css
styledocco: writing previews.js -> /homes/sbertal/sandbox/style/previews.js

Viewing source of the page, I only see the link tag for docs.css and style tag for text/preview.

**Comment by redonkulus** [comment]
NOTE: When I remove the -s flag, the --include file(s) are correctly loaded.

**Comment by jacobrask** [comment]
Ok, cool

The `--include`d files are only included in the preview iframes, so you'd need to change docs.js for your ToC to work.

Do you have any suggestions on where to render the ToC in the 0.5 design?

**Comment by redonkulus** [comment]
I'm basically adding at the top with a `<div id="toc"></div>` tag, for example:

``` /*
# Base

Used to set specific default values instead of resetting everything to zero.

Table of Contents:

<div id="toc" />

 */
```

Since I need the ToC JS on the page itself, I will need to manually copy the docs.js that comes with styledocco with my JS code.

**Comment by redonkulus** [comment]
Also, I'm noticing when I load a page generated by styledocco, I'm getting 370+ http requests. When I remove the docs.js file, all these requests go away. Looks like some type of loop that is requiring all these requests a bunch of times.

**Comment by jacobrask** [comment]
Are you using Chrome? In that case it is because some workarounds I had to do in Chrome/Webkit to get the iframes working.

In other browsers I create an iframe with a data uri and then modify it and get the height after the preview is rendered. Chrome does not allow any kind of communication to or from data uri documents (nor between docs on file:///), so I need to set the iframe src to the current document and then switch its content with the preview content. This means that the docs.js and docs.css files will be loaded once in every iframe before I've switched out the `head` in the iframe.

As I realized this will also mean that some resources will be fetched in the iframes within the iframes, I have some ideas on making this cleaner, like inlining all CSS/JS, but that would also mean bigger HTML files.

**Comment by redonkulus** [comment]
In general, I'd rather see a larger page size than 300 requests. As the requests are causing really long load times. I will get an example URL for you to see.

**Comment by redonkulus** [comment]
I understand this was closed but any update on generating table of contents automatically?

**Comment by jacobrask** [comment]
Yep, it's coming in the next release which I hope will be this or the next weekend.
