### ISSUE TITLE
Access denied in IE

### ISSUE THREAD

**Issue by leandono** [jacobrask/styledocco#49]
Hi, the new system for previews (Styledocco 0.5.0) don't work in IE 9/8 (the error is `“Access is denied”`).

Regards

**Comment by jacobrask** [comment]
Thanks for your report. This particular IE error should now be fixed, but I am probably using other stuff now which will not work in IE<10.

At this stage of the project I want to iterate as quickly as possibly to try out features, so browser compatibility is not the highest priority. For version 1.0 I will decide which browsers versions to support (most likely down to IE8), but I will open separate tickets for that.
