### ISSUE TITLE
Show HTML code in docs, not CSS

### ISSUE THREAD

**Issue by necolas** [jacobrask/styledocco#5]
Rather than showing huge chunks of CSS in the generated docs, you should show the example HTML that is required for the component. This is a standard pattern in almost all toolkit documentation and styleguides that you would manually generate.

A styleguide should be showing other designers / developers the visual outcome and the HTML required to produce it. If you need to know the CSS, you look in the CSS file.

It would also be good to have an option in the CSS comment to decide whether or not to display the example HTML. That way, variants of a component would not end up displaying all the HTML again when you just want to show how a small tweak to a class can make differences.

**Comment by jacobrask** [comment]
I was considering adding an option to hide the CSS and only show the rendered components, but showing the HTML alongside the rendered content indeed makes more sense. Possibly with an option to switch between CSS and HTML.

Regarding options, I'd like to have as little StyleDocco specific syntax as possible, but there might be something Markdown:ish that can be used to suppress output of a particular code snippet - or even something to opt in to output the example code.

I'll investigate and start experimenting in a branch shortly, thanks for the feedback!

**Comment by jacobrask** [comment]
I have thought about this, and I think this makes for a nice flexibility, without introducing any unfamiliar syntax.
- Plain HTML snippets will be rendered as they are now, without showing their source code.
- HTML snippets wrapped in GitHub Markdown code fences (```) will be encoded and shown as a block of example HTML, and not be rendered.

**Comment by necolas** [comment]
Sounds great!

**Comment by jacobrask** [comment]
The recommendation now is that you put code in fences/blocks, and it will both be displayed as code and rendered.
