### ISSUE TITLE
include option not working?

### ISSUE THREAD

**Issue by pjkix** [jacobrask/styledocco#54]
I've been trying to use the `--include` option but it doesn't seem to have any effect :(

trying to include either css or js doesn't seem to do anything to the generated pages or the previews

```
    $ styledocco -n "Style Docs" --verbose --include ../js/contrib/bootstap.min.js less/

```

am I missing something?

**Comment by tonipinel** [comment]
Same happens to me :(

**Comment by elisechant-iconic** [comment]
--include works but only INSIDE previews, not globally
