### ISSUE TITLE
iframe data uri scheme breaks urls without a host

### ISSUE THREAD

**Issue by pjkix** [jacobrask/styledocco#55]
it seems that since the iframes src is a data uri any document relative or even root relative urls without a hostname won't load 

```
<iframe scrolling="no" name="iframe4" src="data:text/html;charset=utf-8,%3C!doctype%20html%3E%3Chtml%3E%3Chead%3E%3C%2Fhead%3E%3C%2Fbody..."></iframe>
```

so css with image or font urls need to include the host as well as the full path which is not really ideal

works:

```
.foo { background: url("http://localhost/img/foo.jpg") ; }
```

wont work: 

```
.foo {  background: url("/img/foo.jpg") ; }
```

perhaps during css parsing the host & port could be inserted for urls? or maybe some other solution?

**Comment by tamala73** [comment]
I have this same issue... is there a work around for it?

**Comment by vytch** [comment]
Same here. It is actually a bit of a show stopper...
Basically, it does not support sprites...
The only way to display images would be to convert the images in data uri format.

**Comment by pjkix** [comment]
@vytch it does support sprites, like i said originally, if you include your host in the path then the images will show up

**Comment by vytch** [comment]
Yes but what i meant  is that most front end dev put relative paths in their css, and this is why sprite wont work. However i like the idea of parsing the css to retrieve background images.

What would be great is to be able to turn all relative paths to abdolute ones so it would work if we open the generated doc as a file.

The idea would be to parse a rendered CSS file for the background images and turn:

```
.foo {  background: url("/img/foo.jpg") ; }
```

to something like:

```
.foo {  background: url("<PATH>/img/foo.jpg") ; }
```

where path is defined in the grunt file.

Vytch

**Comment by vytch** [comment]
Hi

Actually, we might be able to resolve that issue differently.
If we convert all the images into data-uri, then it does not matter whether the documentation is server by a server or just opened as a static file.

There is already a grunt task that turns all images within a css to its data-uri equivalent.
https://github.com/ahomu/grunt-data-uri

Vytch

**Comment by ameego** [comment]
Any update on this apart from the data-uri task?

**Comment by ameego** [comment]
A easy way to proceed is to copy the image folder – as part of grunt build for instance – inside the "docs" folder generated by styledocco. This fixed the issues related to images that I was facing, without changing anything on the sass files.

**Comment by marrs** [comment]
Works for me with the following css

``` css
/*
 h1 documentation

     <h1>Hello</h1>
 */
 h1 {
     background: url(/images/logo.png);
 }
```

Check the formatting of your documentation.  The comment cannot start with spaces; the example should come after a new line and be indented by 4 spaces.

Styledocco will fail silently if the formatting is not correct.  If the example code cannot be resized and is not in an iframe, it's because the comment failed to parse correctly.  I'll address this issue in a separate ticket.
