### ISSUE TITLE
Nicer looking default docs

### ISSUE THREAD

**Issue by necolas** [jacobrask/styledocco#6]
Would be great if the default docs looked nicer and could be split into sections, like KSS

![](http://assets.warpspire.com/images/kss/styleguide-full.png)

Problem with KSS is hardly any front-end devs know how to use it (me included). Your project seems much simpler to get started with and some nice defaults would probably improve the initial adoption rate.

**Comment by jacobrask** [comment]
Agree, and with the changes suggested in #5 it will probably be easier to create a nicer looking design.

Apart from not knowing how to use KSS either, my other problem with it was that for it to be useful it seems like I would have to add KSS syntax to all files in existing projects. That's something I don't want StyleDocco to require, you should be able to get _something_ useful out of it even if you don't have time to go through your entire project.

One way to get optional sections would be to split it up according to Markdown headings or other separators, one could for instance decide that more than 3 dashes in a row means a new section, and that the text following it is a description. A row of dashes is already pretty common practice as a separator in existing stylesheets.

**Comment by necolas** [comment]
I quite like the sound of using the markdown heading syntax, and the general idea of using an existing syntax like markdown to help generate the docs.

**Comment by jacobrask** [comment]
You can check http://jacobrask.github.com/styledocco/ now

I decided to keep the CSS code view, but not as prominent, and I might add a global setting for it to be expanded or not.

The menu also needs some work, I haven't decided the best approach there yet. Any suggestions?

**Comment by j-hernandez** [comment]
Docs are much sexier than first iteration. Solid effort. Will be taking a crack at a style guide using docco this weekend.

**Comment by jacobrask** [comment]
Thanks!
