### ISSUE TITLE
Can't install styledocco

### ISSUE THREAD

**Issue by ghost** [jacobrask/styledocco#71]
Hi, 

I can't install styledocco. I installed Node.js, then npm install -fg styledocco. Doesn't work. I have a lot of errors:

npm ERR!npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/styledocco'
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/styledocco']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/styledocco',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/styledocco',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53',
npm ERR!      'Object.oncomplete (fs.js:107:15)' ] } .. etc etc..

What's wrong?

Regards,

**Comment by dpashkevich** [comment]
It says you have no access to `/usr/local/lib/` etc. If you're installing the module locally, you need root privileges.
Try `sudo npm install -fg styledocco`

**Comment by ghost** [comment]
Works, thx!
