### ISSUE TITLE
imported font faces 

### ISSUE THREAD

**Issue by keilo2000** [jacobrask/styledocco#72]
Is there a way to show imported font faces we using icon fonts and their not see to show up since the path is not showing 

@font-face {
    font-family: 'icomoon';
    src:url('../fonts/icomoon.eot');
    src:url('../fonts/icomoon.eot?#iefix') format('embedded-opentype'),
        url('../fonts/icomoon.woff') format('woff'),
        url('../fonts/icomoon.ttf') format('truetype'),
        url('../fonts/icomoon.svg#icomoon') format('svg');
    font-weight: normal;
    font-style: normal;
}

<em class="icon warning"></em>

icon warning isn't displaying

**Comment by marrs** [comment]
I've submitted a fix for this that be in the next stable release.

**Comment by vsjov** [comment]
This is still not working. Web fonts and Icon-Fonts are not loading
