### ISSUE TITLE
"styledoco watch" option needed

### ISSUE THREAD

**Issue by skynetbinary** [jacobrask/styledocco#76]
I am writing some LESS where I have to generate docs every time I edit it to see my changes in HTML. I have to run styledocco command every time I change anything in LESS. It would be nice if there was a "watch" function which will just watch file changes and update doc files.

**Comment by robinpokorny** [comment]
You want to use [Grunt.js](http://gruntjs.com/) with [grunt-styleguide](https://github.com/indieisaconcept/grunt-styleguide).

**Comment by marrs** [comment]
As @robinpokorny says, there are a number of tools out there that do this already so I'm closing this as wontfix.
