### ISSUE TITLE
Exclude some files

### ISSUE THREAD

**Issue by gregoire-jianda** [jacobrask/styledocco#77]
It would be great to be able to prevent a bunch of files from being parsed.

For example, with the following file structure :

```
css/
    vendor/
          clearless/
                helpers.less
                [...] 
    global.less
    global.css
```

I actually only want to document global.css, no need to document global.less nor the clearless library.

Thanks !

**Comment by marrs** [comment]
You can do this by naming that file explicitly. e.g. `styledocco css/global.css`.  I think this sufficiently covers the need to pick and choose what files to document.
