### ISSUE TITLE
Error running styledocco for the first time

### ISSUE THREAD

**Issue by GarthDB** [jacobrask/styledocco#80]
I installed styledocco and tried to run for the first time and got this error.

The only odd thing I have is the latest stable node installed via nvm.  Not sure if that is causing the issue though.

``` bash
garthdb:styledocco garthdb$ styledocco -n 'tester'

/Users/garthdb/.nvm/v0.10.11/lib/node_modules/styledocco/cli.js:230
    if (err != null) throw new SDError('Could not process files.', err);
                           ^
Error: Could not process files.
Failed to process files.
StyleDocco v0.6.1 running on Node v0.10.11 darwin
```

**Comment by marrs** [comment]
You need to provide a file or directory containing your css as the final argument.  Marking this as a bug as we should be failing gracefully on malformed commands.
