### ISSUE TITLE
Not compiling Sass/Scss?

### ISSUE THREAD

**Issue by luislaborda** [jacobrask/styledocco#81]
Kudos for this fantastic tool. However, I'm encountering the following problem:  When running the command below, I don't see the @includes nor $variables are being processed. Here is an example:

Command:
sudo compass compile && styledocco -n "CSS Styleguide" -o mydocs --preprocessor "sass --compass" sass --verbose

Outputs:
path.exists is now called `fs.exists`.
styledocco: writing sass/_base.scss -> mydocs/base.html
styledocco: writing sass/_colors.scss -> mydocs/colors.html
styledocco: writing sass/_custom.scss -> mydocs/custom.html

But when opening the html pages, I don't see any of see CSS applied in the examples that I have commented in the CSS file. 

To be more specific:

In my .scss I have a variable $image_buttons that points to a path:

$image_buttons: '../images/buttons';

The CSS File

/\* Buttons
    <a class="button">Click Me!</a>
*/
.button {
background: transparent url($image_buttons + "/btn_states.png") no-repeat right -68px;
@include hacked-minimum(width, 320px);
}

The above snippet does not show the background image, nor processing the @includes

Am I missing something?

Thanks

**Comment by marrs** [comment]
Thanks for reporting this issue. The current release is known not to work with relative paths. A fix for this is in master and will be in the next release.

If you need a fix now and can live without relative paths then styledocco will work correctly with absolute paths providing the docs are requested from an http server

**Comment by marrs** [comment]
Fixed by #79
