### ISSUE TITLE
I am unable install styledocco in windows system. I have installed node.js version 0.8.15 and phantom.js with version 1.8.1 in my system. I am using grunt tool to build my javascript, html and css code. I have installed 0.3.17 version of grunt in my syste

### ISSUE THREAD

**Issue by rashmi1988** [jacobrask/styledocco#94]

**Comment by rashmi1988** [comment]
I am using the following command to install styledocco :  npm install -g styledocco.. I am getting the following error :  
C:\Users\396103>npm install -g styledocco
npm http GET https://registry.npmjs.org/styledocco
npm http 304 https://registry.npmjs.org/styledocco
npm ERR! git clone git://github.com/marrs/node-findit.git CreateProcessW: The sy
stem cannot find the file specified.
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/clean-css
npm http GET https://registry.npmjs.org/marked
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/jade
npm http GET https://registry.npmjs.org/uglify-js
npm ERR! Error: `git "clone" "git://github.com/marrs/node-findit.git" "C:\\Users
\\396103\\AppData\\Local\\Temp\\npm-5212\\1377171899751-0.49915334885008633"` fa
iled with 127
npm ERR!     at ChildProcess.<anonymous> (c:\Program Files (x86)\nodejs\node_mod
ules\npm\lib\utils\exec.js:56:20)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:99:17)
npm ERR!     at Process._handle.onexit (child_process.js:678:10)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\Program Files (x86)\nodejs\\node.exe" "c:\Program File
s (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "styledocco"

npm ERR! cwd C:\Users\396103
npm ERR! node -v v0.8.15
npm ERR! npm -v 1.1.66
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/clean-css
npm http 304 https://registry.npmjs.org/jade
npm WARN package.json jade@0.23.0 No README.md file found!
npm http 304 https://registry.npmjs.org/marked
npm http 304 https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/mkdirp
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\396103\npm-debug.log
npm ERR! not ok code 0

**Comment by marrs** [comment]
Does it work if you try installing it again?

**Comment by rashmi1988** [comment]
No.. I am getting the same error. I am able to install styledocco in Mac but its failing in Windows

**Comment by marrs** [comment]
Can you run `git clone git://github.com/marrs/node-findit.git` at your command prompt and tell me what it returns?
